//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightNotes.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodEntityContainer : DbContext
    {
        public FoodEntityContainer()
            : base("name=FoodEntityContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Food> FoodSet { get; set; }
        public DbSet<Genre> GenreSet { get; set; }
        public DbSet<Person> PersonSet { get; set; }
        public DbSet<Meal> MealSet { get; set; }
        public DbSet<Meals> MealsSet { get; set; }
    }
}
