//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightNotes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public double EnergyValue { get; set; }
        public double Weight { get; set; }
        public string WeightType { get; set; }
        public double Carbohydrates { get; set; }
        public double Protein { get; set; }
        public double Fat { get; set; }
        public double Fibers { get; set; }
        public double Sodium { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Meal Meal { get; set; }
    }
}
