//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightNotes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meals
    {
        public Meals()
        {
            this.Meal = new HashSet<Meal>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Meal> Meal { get; set; }
    }
}
