//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightNotes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public Meal()
        {
            this.Food = new HashSet<Food>();
        }
    
        public int Id { get; set; }
        public string TypeOfMeal { get; set; }
    
        public virtual Meals Meals { get; set; }
        public virtual ICollection<Food> Food { get; set; }
    }
}
