//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightNotes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public long WeightWatchersCode { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public bool SexualGender { get; set; }
        public double Weight { get; set; }
        public double Height { get; set; }
        public double TargetHeight { get; set; }
    }
}
